### ISSUE TITLE
Fails on code run through uglify

### ISSUE THREAD

**Issue by mathisonian** [miguelmota/is-class#3]
Thanks for the module, it is super useful. I've been using it in my project, but we've recently hit an error where the `isClass` check fails when code has been uglified https://github.com/idyll-lang/idyll/issues/124. Any ideas for this? Happy to work on a patch

**Comment by mathisonian** [comment]
I'm able to get this to work by passing the following options to uglify: `uglify({mangle: { keep_fnames: true} })`

**Comment by miguelmota** [comment]
@mathisonian if you're using babel, it's because babel converts es6 classes to functions, using `_classCallCheck` as the function name (which is what `isClass` looks for). Mangling the function names will of course change the name so therefore it'll fail. 

Your workaround is good. You can also make Uglifyjs skip mangling certain functions names:

 ```js
 mangle: {
    except: ['_classCallCheck']
 } 
```

if using cli:

```bash
uglifyjs --mangle reserved=['_classCallCheck']
```
